package com.jwtAuthEx.jwtPrac.controller;

import com.jwtAuthEx.jwtPrac.entity.User;
import com.jwtAuthEx.jwtPrac.payload.UserRequest;
import com.jwtAuthEx.jwtPrac.payload.UserResponse;
import com.jwtAuthEx.jwtPrac.service.IUserService;
import com.jwtAuthEx.jwtPrac.util.JwtUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.security.Principal;

@RestController
@RequestMapping("/user")
public class UserController {

    @Autowired
    private AuthenticationManager authenticationManager;

    @Autowired
    private IUserService iUserServicer;

    @Autowired
    private JwtUtil jwtUtil;


    @PostMapping("/save")
    public ResponseEntity<String> saveUser(@RequestBody User user){
        iUserServicer.saveUser(user);
        return ResponseEntity.ok("User Created");
//                return new ResponseEntity<String>("User Created", HttpStatus.OK);
    }

    @PostMapping("/login")
    public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest userRequest){
        authenticationManager.authenticate(new UsernamePasswordAuthenticationToken(
                userRequest.getUsername(),
                userRequest.getPassword()
        ));
        String token = jwtUtil.generatedToken(userRequest.getUsername());

        return ResponseEntity.ok(new UserResponse(token, "Generated by ANrag"));
    }

    @PostMapping("/welcome")
    public ResponseEntity<String> showUserData(Principal p ){
        return ResponseEntity.ok("Hello :" + p.getName());
    }
//TODO : user login test
}
